//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yolcuTakipSistemi02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        public int sirketId { get; set; }
        public string sirketAdi { get; set; }
    
        public virtual Yolcu Yolcu { get; set; }
    }
}
