//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yolcuTakipSistemi02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yolcu()
        {
            this.Sirket = new HashSet<Sirket>();
        }
    
        public int yolcuId { get; set; }
        public string adSoyad { get; set; }
        public string bilgi { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int ucusId { get; set; }
        public int uyeId { get; set; }
    
        public virtual Ucus Ucus { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sirket> Sirket { get; set; }
    }
}
